In [1]:
#  Numpy is funcdamental package for scientific computing in python .
# What is numpy?
# NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

# At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

In [2]:
# Numpy Arrays Vs Python Sequences
## NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

## The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

## NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

## A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [3]:
# Importing numpy library
import numpy as np

In [4]:
# Creation of numpy array using different techniques
arr_0 = np.arange(1,10,2)
print(arr_0)
print(type(arr_0))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [5]:
arr_1 = np.linspace(1,10,10)
print(arr_1)
print(type(arr_1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [6]:
# 2-d array
arr_2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr_2)
print(type(arr_2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [7]:
# 3-d array or tensor
arr_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [9]:
np.array([1,0,0,1,1,1,0],dtype = bool)

array([ True, False, False,  True,  True,  True, False])

In [10]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
# reshape
a = np.arange(1,11).reshape(5,2)
print(a.ndim)

2


In [12]:
# np.ones and np.zeros # to initialize values in deep learning (weights)
print(np.ones((5,2)))
print(np.zeros((5,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
# np.random
np.random.random((3,4))

array([[0.67727649, 0.59499317, 0.95987007, 0.27946675],
       [0.68393404, 0.05423305, 0.47920474, 0.23849638],
       [0.37867697, 0.3419007 , 0.84020292, 0.43580726]])

In [14]:
# identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Array attributes
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8,dtype = np.int64).reshape(2,2,2)

In [43]:
# ndim
print(np.ndim(a1),'a1')
print(np.ndim(a2),'a2')
print(np.ndim(a3),'a3')
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1 a1
2 a2
3 a3
1
2
3


In [49]:
# shape
print('a1',a1.shape)
print('a2',a2.shape)
print('a3',a3.shape)
print(np.shape(a1))
print(np.shape(a2))
print(np.shape(a3))

a1 (10,)
a2 (3, 4)
a3 (2, 2, 2)
(10,)
(3, 4)
(2, 2, 2)


In [51]:
# size 
print('a1',a1.size)
print('a2',a2.size)
print('a3',a3.size)

a1 10
a2 12
a3 8


In [54]:
# item size
print('a1',a1.itemsize)
print('a2',a2.itemsize)
print('a3',a3.itemsize)

a1 4
a2 8
a3 8


In [55]:
# dtype
print('a1',a1.dtype)
print('a2',a2.dtype)
print('a3',a3.dtype)

a1 int32
a2 float64
a3 int64


In [61]:
# Changing Data Type
# astype --> used for memory optimisation
print(a3.dtype)
print(a3.astype(np.int16))
print(a3.dtype)

int64
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int64


In [62]:
# array operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [63]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
# scalar operations
# arithmatic
print(a1*2)
print(a1//2)
print(a1/2)
print(a1%2)
print(a1 + 2)
print(a1 - 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


In [67]:
# relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
# Vector operations
# arithmatic
print(a1 + a2)
print(a2 - a1)
print(a1*a2)
print(a1/a2)


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [69]:
# relational
a1 > a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [70]:
# Array Functions 

In [71]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[33.  3. 32.]
 [ 9. 29. 84.]
 [99. 14. 21.]]


In [73]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

99.0
3.0
324.0
2021563982592.0


In [74]:
# max/min/sum/prod to find the axis row wise
print(np.max(a1,axis = 1))
print(np.min(a1,axis = 1))
print(np.sum(a1,axis = 1))
print(np.prod(a1,axis = 1))

[33. 84. 99.]
[ 3.  9. 14.]
[ 68. 122. 134.]
[ 3168. 21924. 29106.]


In [75]:
# max/min/sum/prod to find the axis column wise
print(np.max(a1,axis = 0))
print(np.min(a1,axis = 0))
print(np.sum(a1,axis = 0))
print(np.prod(a1,axis = 0))

[99. 29. 84.]
[ 9.  3. 21.]
[141.  46. 137.]
[29403.  1218. 56448.]


In [78]:
# mean/median/std/var
print(np.mean(a1,axis = 1))
print(np.median(a1,axis = 1))
print(np.std(a1,axis = 1))
print(np.var(a1,axis = 1))

[22.66666667 40.66666667 44.66666667]
[32. 29. 21.]
[13.9124245  31.71049598 38.52560476]
[ 193.55555556 1005.55555556 1484.22222222]


In [80]:
# dot product
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(4,3)
np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [81]:
# log and exponent
print(np.log(a1))
print(np.exp(a1))

[[3.49650756 1.09861229 3.4657359 ]
 [2.19722458 3.36729583 4.4308168 ]
 [4.59511985 2.63905733 3.04452244]]
[[2.14643580e+14 2.00855369e+01 7.89629602e+13]
 [8.10308393e+03 3.93133430e+12 3.02507732e+36]
 [9.88903032e+42 1.20260428e+06 1.31881573e+09]]


In [83]:
a = np.random.random((2,3))*100
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[[79. 52.  3.]
 [64. 95. 95.]]
[[78. 51.  2.]
 [64. 94. 95.]]
[[79. 52.  3.]
 [65. 95. 96.]]


In [84]:
# Indexing and Slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [85]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [101]:
# 1d array
print(a1[-1])
print(a1[0:3])

9
[0 1 2]


In [93]:
# 2d array
print(a2[0][0:2])
print(a2[1][-2])
print(a2[2][-1])
print(a2[1][0])

[0 1]
6
11
4


In [100]:
# 3d array
print(a3[0][0][1])
print(a3[0][0])
print(a3[1][1][0])
# another method
print(a3[1,1,0])

1
[0 1]
6
6


In [113]:
# slicing
# 1d array
print(a1[2:5])
# 2d array
print(a2[0:2,0:2])
print(a2[1,:])
print(a2[:,2])
print(a2[1:,1:3])
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[0:2,1:])



[2 3 4]
[[0 1]
 [4 5]]
[4 5 6 7]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[[1 2 3]
 [5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [125]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)
print()
print('In between array ',a3[1,:,:],sep = '\n')
print()
print('Another between array ',a3[::2,:,:],sep = '\n')
print()
print('In between column',a3[1,:,1],sep = '\n')
print()
print('Another example',a3[2,1:,1:],sep = '\n')
print()
print('Yet another example',a3[::2,0,::2],sep = '\n')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

In between array 
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

Another between array 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

In between column
[10 13 16]

Another example
[[22 23]
 [25 26]]

Yet another example
[[ 0  2]
 [18 20]]


In [128]:
# Iterating --> 1d array
print(a1)
for i in a1:
    print(i,type(i))

[0 1 2 3 4 5 6 7 8 9]
0 <class 'numpy.int32'>
1 <class 'numpy.int32'>
2 <class 'numpy.int32'>
3 <class 'numpy.int32'>
4 <class 'numpy.int32'>
5 <class 'numpy.int32'>
6 <class 'numpy.int32'>
7 <class 'numpy.int32'>
8 <class 'numpy.int32'>
9 <class 'numpy.int32'>


In [131]:
# Iterating --> 2d array
print(a2)
for i in a2:
    print(i,type(i))

# looping through each item in 2 d array
for i in np.nditer(a2):
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3] <class 'numpy.ndarray'>
[4 5 6 7] <class 'numpy.ndarray'>
[ 8  9 10 11] <class 'numpy.ndarray'>
0
1
2
3
4
5
6
7
8
9
10
11


In [132]:
# Iterating --> 3d array
print(a3)
for i in a3:
    print(i,type(i))
    
# looping through each item in 3 d array
for i in np.nditer(a3):
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>
[[ 9 10 11]
 [12 13 14]
 [15 16 17]] <class 'numpy.ndarray'>
[[18 19 20]
 [21 22 23]
 [24 25 26]] <class 'numpy.ndarray'>
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [142]:
# Iterator --> nditer
x = np.nditer(a3)
print('__iter__' in dir(x))
print('__next__' in dir(x))
for i in x:
    print(i)

True
True
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [153]:
# Reshaping
# reshape
print('Reshape',np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3)),sep = '\n')
# transpose
print('original',a2,sep = '\n')
print('Transpose',a2.T,sep = '\n')
print('Another way to Transpose',np.transpose(a2),sep = '\n')
# ravel --> converts array into 1 d array
print('Ravel 2d array',np.ravel(a2),sep = '\n')
print('Ravel 3d array',np.ravel(a3),sep = '\n')

Reshape
[[1 2 3]
 [4 5 6]
 [7 8 9]]
original
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Another way to Transpose
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Ravel 2d array
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel 3d array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [154]:
# Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

# horizontal stacking
print(np.hstack((a4,a5)))

# vertical stacking
print(np.vstack((a4,a5)))

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [161]:
# Spliting 
a6 = np.hstack((a4,a5))
# horizontal spliting
print(a6)
np.hsplit(a6,4)
# vertical split
np.vsplit(a6,3)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]

In [16]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a1[2:5]

array([2, 3, 4])

In [18]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
a2[0::2,0::2]

array([[ 0.,  2.],
       [ 8., 10.]])

In [22]:
a2[0::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [24]:
a2[:,2]

array([ 2.,  6., 10.])

In [25]:
a2[0::2,0::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [27]:
a2[0::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])