In [1]:
# np.sort
# Return a sorted copy of an array.

# https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np
a = np.random.randint(1,100,12)
a

array([60, 28, 68, 89, 86, 26, 33, 38, 68,  8, 48, 12])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[57, 72, 20, 23],
       [68, 88, 71, 66],
       [40, 52, 94, 67],
       [57,  7, 62, 78],
       [37,  8, 46, 33],
       [81, 64, 70, 90]])

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.sort(a,axis = 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
x = np.random.randint(1,100,15)
x = x.reshape(3,5)
x

array([[55, 52,  1,  1, 59],
       [37, 40, 82, 66, 24],
       [89,  2, 19, 76, 86]])

In [18]:
np.sort(x,axis= 1)

array([[ 1,  1, 52, 55, 59],
       [24, 37, 40, 66, 82],
       [ 2, 19, 76, 86, 89]])

In [19]:
# np.append()
a = np.random.randint(1,100,12)
a
np.append(a,200)

array([ 57,  56,  45,   8,  46,  50,  34,  18,  94,  66,  24,  15, 200])

In [20]:
x

array([[55, 52,  1,  1, 59],
       [37, 40, 82, 66, 24],
       [89,  2, 19, 76, 86]])

In [25]:
np.append(x,np.zeros(3,1))

TypeError: Cannot interpret '1' as a data type

In [30]:
y = np.zeros((3,1))
y

array([[0.],
       [0.],
       [0.]])

In [29]:
np.append(x,y,axis = 1)

array([[55., 52.,  1.,  1., 59.,  0.],
       [37., 40., 82., 66., 24.,  0.],
       [89.,  2., 19., 76., 86.,  0.]])

In [31]:
# np.concatenate

In [32]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [34]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
# np.unique
a = np.array([1,2,3,4,5,1,1,1,2,2,2,3,3,3,4,4,5,6,7,8,7,7,6,5,4,3,8,9,9,0,0,0,9])
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# np.expand_dims
a = np.arange(24).reshape(24,)
print(a)
print(np.expand_dims(a,axis=1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [41]:
a = np.array([1,2,3,4,50,10,11,12,25,52,62,73,23,33,44,54,55,66,71,58,87,78,65,54,41,33,80,99,19,10,70,50,91])
np.where(a > 50)


(array([ 9, 10, 11, 15, 16, 17, 18, 19, 20, 21, 22, 23, 26, 27, 30, 32],
       dtype=int64),)

In [44]:
# Replace values
np.where(a>=50,0,a)

array([ 1,  2,  3,  4,  0, 10, 11, 12, 25,  0,  0,  0, 23, 33, 44,  0,  0,
        0,  0,  0,  0,  0,  0,  0, 41, 33,  0,  0, 19, 10,  0,  0,  0])

In [45]:
x

array([[55, 52,  1,  1, 59],
       [37, 40, 82, 66, 24],
       [89,  2, 19, 76, 86]])

In [48]:
# Argmax
np.argmax(x,axis = 1)

array([4, 2, 0], dtype=int64)

In [47]:
np.argmax(x,axis = 0)

array([2, 0, 1, 2, 2], dtype=int64)

In [49]:
np.argmin(x,axis = 1)

array([2, 4, 1], dtype=int64)

In [50]:
np.cumsum(x,axis = 1)

array([[ 55, 107, 108, 109, 168],
       [ 37,  77, 159, 225, 249],
       [ 89,  91, 110, 186, 272]])

In [51]:
np.cumprod(x,axis = 1)

array([[       55,      2860,      2860,      2860,    168740],
       [       37,      1480,    121360,   8009760, 192234240],
       [       89,       178,      3382,    257032,  22104752]])

In [52]:
np.cumproduct(x,axis = 1)

array([[       55,      2860,      2860,      2860,    168740],
       [       37,      1480,    121360,   8009760, 192234240],
       [       89,       178,      3382,    257032,  22104752]])

In [53]:
a

array([ 1,  2,  3,  4, 50, 10, 11, 12, 25, 52, 62, 73, 23, 33, 44, 54, 55,
       66, 71, 58, 87, 78, 65, 54, 41, 33, 80, 99, 19, 10, 70, 50, 91])

In [59]:
np.percentile(a,50)

50.0

In [60]:
np.histogram(a,bins =[0,10,20,30,40,50,60,70,80,90,100])

(array([4, 5, 2, 2, 2, 7, 3, 4, 2, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [61]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [62]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [63]:
a

array([ 1,  2,  3,  4, 50, 10, 11, 12, 25, 52, 62, 73, 23, 33, 44, 54, 55,
       66, 71, 58, 87, 78, 65, 54, 41, 33, 80, 99, 19, 10, 70, 50, 91])

In [67]:
a[np.isin(a,[50,60,70,80,90])]

array([50, 80, 70, 50])

In [68]:
x 

array([[55, 52,  1,  1, 59],
       [37, 40, 82, 66, 24],
       [89,  2, 19, 76, 86]])

In [71]:
np.flip(x,axis = 1)

array([[59,  1,  1, 52, 55],
       [24, 66, 82, 40, 37],
       [86, 76, 19,  2, 89]])

In [77]:
np.put(x,[0,1],59)
x

array([[59, 59,  1,  1, 59],
       [37, 40, 82, 66, 24],
       [89,  2, 19, 76, 86]])

In [78]:
a

array([56,  2,  3,  4, 50, 10, 11, 12, 25, 52, 62, 73, 23, 33, 44, 54, 55,
       66, 71, 58, 87, 78, 65, 54, 41, 33, 80, 99, 19, 10, 70, 50, 91])

In [79]:
np.delete(a,0)

array([ 2,  3,  4, 50, 10, 11, 12, 25, 52, 62, 73, 23, 33, 44, 54, 55, 66,
       71, 58, 87, 78, 65, 54, 41, 33, 80, 99, 19, 10, 70, 50, 91])

In [82]:
np.delete(x,0,axis = 1)

array([[59,  1,  1, 59],
       [40, 82, 66, 24],
       [ 2, 19, 76, 86]])

In [83]:
# Set functions

In [84]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [85]:
np.intersect1d(a,b)

array([3, 4, 5])

In [86]:
np.setdiff1d(a,b)

array([1, 2])

In [87]:
np.setdiff1d(b,a)

array([6, 7])

In [88]:
np.setxor1d(a,b)

array([1, 2, 6, 7])

In [90]:
np.in1d(a,9)

array([False, False, False, False, False])

In [95]:
a = np.array([1,2,3,4,50,10,11,12,25,52,62,73,23,33,44,54,55,66,71,58,87,78,65,54,41,33,80,99,19,10,70,50,91])
np.clip(a,a_min=25,a_max=75)

array([25, 25, 25, 25, 50, 25, 25, 25, 25, 52, 62, 73, 25, 33, 44, 54, 55,
       66, 71, 58, 75, 75, 65, 54, 41, 33, 75, 75, 25, 25, 70, 50, 75])