In [1]:
# How to create numpy arrays

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
import sys

In [7]:
sys.version

'3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]'

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
# Initialising numpy array with zeros
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Initializing numpy arrays with ones
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
arr5 = np.identity(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
arr6 = np.arange(10)
print(arr6)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr7 = np.arange(2,15,3)
print(arr7)

[ 2  5  8 11 14]


In [14]:
arr8 = np.linspace(0,10,5)
print(arr8)

[ 0.   2.5  5.   7.5 10. ]


In [15]:
arr9 = arr8.copy()

In [16]:
print(arr9)

[ 0.   2.5  5.   7.5 10. ]


In [17]:
arr9[1] = 15

In [18]:
arr9 

array([ 0. , 15. ,  5. ,  7.5, 10. ])

In [19]:
arr8

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
# Attributes of numpy array
arr1
arr1.shape

(5,)

In [22]:
arr8.shape

(5,)

In [23]:
arr5.shape

(5, 5)

In [26]:
arr2.shape

(2, 3)

In [27]:
arr9 = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

In [28]:
arr9.shape

(2, 2, 2)

In [31]:
# Dimension of matrix
arr9.ndim

3

In [30]:
arr2.ndim

2

In [34]:
# Number of items
arr1.size

5

In [35]:
arr9.size

8

In [37]:
# Size of each item
arr9.itemsize

4

In [38]:
# Data Type
arr8.dtype

dtype('float64')

In [39]:
arr9.dtype

dtype('int32')

In [42]:
arr10 = arr9.astype('float64')
arr10.dtype

dtype('float64')

In [41]:
arr9.dtype

dtype('int32')

In [49]:
lst_a = range(100000)
arr11 = np.arange(100000)

In [50]:
import sys

In [51]:
sys.getsizeof(87)*len(lst_a)


2800000

In [52]:
arr11.itemsize*arr11.size

400000

In [63]:
import time
x = range(100000000)
y = range(100000000,200000000)

start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print(time.time()- start_time)

7.549253463745117


In [64]:
a = np.arange(1000000000)
b = np.arange(1000000000,2000000000)
start_time = time.time()

c =a+b

print(time.time()- start_time)

83.28279638290405


In [65]:
arr11

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [66]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
arr9.size

8

In [68]:
arr9.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
arr9.reshape(4,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]])

In [72]:
arr0 = np.arange(24).reshape(6,4)

In [73]:
arr0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
arr0[:,1]

array([ 1,  5,  9, 13, 17, 21])

In [77]:
arr0[-2:,:]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
arr0[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [79]:
arr0[-2:,-2:]

array([[18, 19],
       [22, 23]])

In [80]:
arr0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
for i in arr0:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [84]:
for i in np.nditer(arr0):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
