
#### np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np

In [4]:
a = np.random.randint(0,100,15)

In [5]:
a

array([79, 92, 48, 13, 24, 43, 95,  2, 10, 33, 56,  9, 15, 87, 88])

In [8]:
b = np.random.randint(0,100,24).reshape(4,6)

In [9]:
b

array([[77, 37, 63, 34, 19, 68],
       [18,  4, 59, 46, 91, 62],
       [60, 54, 11, 79, 12, 81],
       [12, 96, 31, 76, 72, 72]])

In [10]:
np.sort(a)

array([ 2,  9, 10, 13, 15, 24, 33, 43, 48, 56, 79, 87, 88, 92, 95])

In [11]:
np.sort(a)[::-1]

array([95, 92, 88, 87, 79, 56, 48, 43, 33, 24, 15, 13, 10,  9,  2])

In [13]:
np.sort(b,axis = 0)

array([[12,  4, 11, 34, 12, 62],
       [18, 37, 31, 46, 19, 68],
       [60, 54, 59, 76, 72, 72],
       [77, 96, 63, 79, 91, 81]])

In [14]:
np.sort(b,axis = 1)

array([[19, 34, 37, 63, 68, 77],
       [ 4, 18, 46, 59, 62, 91],
       [11, 12, 54, 60, 79, 81],
       [12, 31, 72, 72, 76, 96]])

#### np.append
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [15]:
np.append(a,[1,2,3])

array([79, 92, 48, 13, 24, 43, 95,  2, 10, 33, 56,  9, 15, 87, 88,  1,  2,
        3])

In [16]:
np.append(a,200)

array([ 79,  92,  48,  13,  24,  43,  95,   2,  10,  33,  56,   9,  15,
        87,  88, 200])

In [26]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[77., 37., 63., 34., 19., 68.,  1.],
       [18.,  4., 59., 46., 91., 62.,  1.],
       [60., 54., 11., 79., 12., 81.,  1.],
       [12., 96., 31., 76., 72., 72.,  1.]])

#### np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [30]:
a = np.random.random(12).reshape(3,4)
b = np.random.random(12).reshape(3,4)

In [31]:
a

array([[0.81195187, 0.47364814, 0.46423469, 0.47335273],
       [0.90826893, 0.80995467, 0.94618917, 0.90613734],
       [0.25056178, 0.48926709, 0.49363865, 0.93596392]])

In [32]:
b

array([[0.87796658, 0.30517297, 0.32633987, 0.0714547 ],
       [0.6482254 , 0.12486163, 0.30973062, 0.7165809 ],
       [0.17797812, 0.98852977, 0.95872006, 0.87328215]])

In [36]:
np.concatenate((a,b),axis = 1)

array([[0.81195187, 0.47364814, 0.46423469, 0.47335273, 0.87796658,
        0.30517297, 0.32633987, 0.0714547 ],
       [0.90826893, 0.80995467, 0.94618917, 0.90613734, 0.6482254 ,
        0.12486163, 0.30973062, 0.7165809 ],
       [0.25056178, 0.48926709, 0.49363865, 0.93596392, 0.17797812,
        0.98852977, 0.95872006, 0.87328215]])

In [37]:
np.concatenate((a,b),axis = 0)

array([[0.81195187, 0.47364814, 0.46423469, 0.47335273],
       [0.90826893, 0.80995467, 0.94618917, 0.90613734],
       [0.25056178, 0.48926709, 0.49363865, 0.93596392],
       [0.87796658, 0.30517297, 0.32633987, 0.0714547 ],
       [0.6482254 , 0.12486163, 0.30973062, 0.7165809 ],
       [0.17797812, 0.98852977, 0.95872006, 0.87328215]])

#### np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [38]:
a = np.array([1,1,1,1,2,2,2,3,3,3,4,4,4,5,5,6,7,8,8,8,8,9,9,9,9])

In [39]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [40]:
a = np.arange(1,30,2)

In [41]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [43]:
np.shape(np.expand_dims(a,axis = 1))

(15, 1)

#### np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [44]:
a = np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [46]:
np.where(a > 50,1,a)

array([11,  1, 28, 50, 38, 37,  1,  1,  5, 30,  1,  9,  1,  2, 21])


#### np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [47]:
np.argmax(a)

6

In [48]:
np.argmin(a)

13

In [49]:
b

array([[0.87796658, 0.30517297, 0.32633987, 0.0714547 ],
       [0.6482254 , 0.12486163, 0.30973062, 0.7165809 ],
       [0.17797812, 0.98852977, 0.95872006, 0.87328215]])

In [52]:
np.argmax(b,axis = 1)

array([0, 3, 1], dtype=int64)

In [53]:
np.argmax(b,axis = 0)

array([0, 2, 2, 2], dtype=int64)

#### np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [54]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616], dtype=int32)

In [55]:
np.cumsum(b,axis = 1)

array([[0.87796658, 1.18313955, 1.50947942, 1.58093412],
       [0.6482254 , 0.77308703, 1.08281764, 1.79939854],
       [0.17797812, 1.16650789, 2.12522794, 2.9985101 ]])

In [56]:
np.cumprod(a)

array([         11,         583,       16324,      816200,    31015600,
        1147577200,   498074400, -1421795456,  1480957312,  1479046400,
        1790907392, -1061702656, -1208428544,  1878110208,   785608704],
      dtype=int32)

In [57]:
np.cumprod(b,axis = 0)

array([[0.87796658, 0.30517297, 0.32633987, 0.0714547 ],
       [0.56912023, 0.03810439, 0.10107745, 0.05120308],
       [0.10129095, 0.03766733, 0.09690498, 0.04471473]])

#### np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [58]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [60]:
np.percentile(a,25)

16.0

In [61]:
np.sort(a)

array([ 2,  5,  9, 11, 21, 28, 30, 37, 38, 50, 53, 68, 78, 92, 94])

In [62]:
np.percentile(a,50)

37.0

In [63]:
np.percentile(a,100)

94.0

##### np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [64]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [65]:
np.histogram(a,[0,25,50,75,100])

(array([5, 4, 3, 3], dtype=int64), array([  0,  25,  50,  75, 100]))

#### np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [66]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [67]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

#### np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [68]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [71]:
x = np.isin(a,[0,10,20,30,40,50,60,70,80,100])

In [73]:
a[x]

array([50, 30])

###### np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [74]:
a 

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [75]:
np.flip(a)

array([21,  2, 78,  9, 68, 30,  5, 92, 94, 37, 38, 50, 28, 53, 11])

In [76]:
b

array([[0.87796658, 0.30517297, 0.32633987, 0.0714547 ],
       [0.6482254 , 0.12486163, 0.30973062, 0.7165809 ],
       [0.17797812, 0.98852977, 0.95872006, 0.87328215]])

In [77]:
np.flip(b)

array([[0.87328215, 0.95872006, 0.98852977, 0.17797812],
       [0.7165809 , 0.30973062, 0.12486163, 0.6482254 ],
       [0.0714547 , 0.32633987, 0.30517297, 0.87796658]])

In [78]:
np.flip(b,axis = 1)

array([[0.0714547 , 0.32633987, 0.30517297, 0.87796658],
       [0.7165809 , 0.30973062, 0.12486163, 0.6482254 ],
       [0.87328215, 0.95872006, 0.98852977, 0.17797812]])

#### np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [79]:
a 

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [80]:
np.put(a,[0,1],[19,99])

In [81]:
a

array([19, 99, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

#### np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [82]:
a

array([19, 99, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [83]:
np.delete(a,[-1,-2])

array([19, 99, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78])

#### Set functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [84]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [85]:
np.intersect1d(m,n)

array([3, 4, 5])

In [86]:
np.setdiff1d(m,n)

array([1, 2])

In [87]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [88]:
np.in1d(m,n)

array([False, False,  True,  True,  True])

###### np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [92]:
a

array([19, 99, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [90]:
x = np.array([2,23,45,54,65,22,34,78,98,50,40,85,92,32])

In [91]:
np.clip(x,a_min = 25,a_max= 75)

array([25, 25, 45, 54, 65, 25, 34, 75, 75, 50, 40, 75, 75, 32])