##### What is Numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

##### Numpy Arrays Vs Python Sequences
- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
# Creating numpy array
# 1d array
# Vector
import numpy as np

new_array = np.array([1,2,3,4,5])
print(new_array,type(new_array))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
# 2d and 3d array
# 2d array is matrices
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3d array is a tensor 
array_3d = np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(array_3d)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [7]:
# dtype
print(np.array([1,2,3],dtype = float))
print(np.array([1,2,3],dtype = bool))
print(np.array([1,2,3],dtype = complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [8]:
# Range between two numbers
print(np.arange(1,11))
print(np.arange(1,11,2))

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [9]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
print(np.arange(1,13).reshape(2,6))
print(np.arange(1,13).reshape(4,3))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
# np.ones and np.zeros
# Can be used to initialize arrays
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# Initialize with random numbers
np.random.random((3,4))

array([[0.58606305, 0.83673903, 0.63459712, 0.38419417],
       [0.06058418, 0.33333803, 0.40032825, 0.94125377],
       [0.50919882, 0.81908931, 0.63168347, 0.76826936]])

In [21]:
# np.linspace - linearly spaced numbers
np.linspace(-10,10,10, dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [20]:
#### np.identity 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# Array Attributes

In [38]:
a1 = np.arange(10,dtype = int)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(1,9,dtype = int).reshape(2,2,2)

In [39]:
# ndim 
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [40]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a3) # 2 2-d arrays

(10,)
(3, 4)
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [42]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [45]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [50]:
# Changing Datatype
a3.dtype
a3.astype(np.int32)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
# Array operation 
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [54]:
# scalar opeations 
# Arithmatic
print(a1*2)
print(a1)
print(a1+2)
print(a1/2)
print(a1%2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [56]:
# relational operations on numpy array
a2 > 17

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [60]:
# Vector operations
# Arithmatic
print(a1 + a2)
print(a1*a2)
print(a2-a1)
print(a1/a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [61]:
# relational
a2 > a1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
# Array Function
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[52.  2. 15.]
 [33. 99. 37.]
 [19. 31. 13.]]


In [71]:
np.max(a1)
print(np.max(a1,axis = 1)) # min in row
print(np.max(a1,axis = 0)) # min in column

[52. 99. 31.]
[52. 99. 37.]


In [70]:
np.min(a1)
print(np.min(a1,axis = 1)) # min in row
print(np.min(a1,axis = 0)) # min in column

[ 2. 33. 13.]
[19.  2. 13.]


In [72]:
np.sum(a1)
print(np.sum(a1,axis = 1)) # min in row
print(np.sum(a1,axis = 0)) # min in column

[ 69. 169.  63.]
[104. 132.  65.]


In [68]:
np.prod(a1)

1443889984680.0

In [73]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

33.44444444444444
31.0
27.11338788254127
735.1358024691358


In [76]:
# Trignometric fuctions
print(np.sin(a1))
print(np.tan(a1))
print(np.cos(a1))
print(np.sin(a1) + np.cos(a1))

[[ 0.98662759  0.90929743  0.65028784]
 [ 0.99991186 -0.99920683 -0.64353813]
 [ 0.14987721 -0.40403765  0.42016704]]
[[ -6.05327238  -2.18503986  -0.8559934 ]
 [-75.3130148  -25.09253498  -0.84077126]
 [  0.15158947  -0.44169557   0.46302113]]
[[-0.16299078 -0.41614684 -0.75968791]
 [-0.01327675  0.03982088  0.76541405]
 [ 0.98870462  0.91474236  0.90744678]]
[[ 0.82363681  0.49315059 -0.10940007]
 [ 0.98663511 -0.95938595  0.12187592]
 [ 1.13858183  0.51070471  1.32761382]]


In [78]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [79]:
# log and exponents
np.log(a1)
np.exp(a1)


array([[3.83100800e+22, 7.38905610e+00, 3.26901737e+06],
       [2.14643580e+14, 9.88903032e+42, 1.17191424e+16],
       [1.78482301e+08, 2.90488497e+13, 4.42413392e+05]])

In [85]:
# round /floor/ceil
a = np.random.random((2,3))*100
print(a)

[[41.09038295 97.02469888  0.38271463]
 [73.24407253 30.01720914 39.33008577]]


In [86]:
np.round(a)


array([[41., 97.,  0.],
       [73., 30., 39.]])

In [87]:
np.floor(a)

array([[41., 97.,  0.],
       [73., 30., 39.]])

In [88]:
np.ceil(a)

array([[42., 98.,  1.],
       [74., 31., 40.]])

In [2]:
# Indexing and Slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Positive Indexing
a1[0]


0

In [5]:
# Negative Indexing
a1[-1]

9

In [6]:
# Indexing in 2d array
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
a2[1,2]

6

In [9]:
a2[2,3]

11

In [10]:
a2[1,0]

4

In [11]:
a2[1,1]

5

In [12]:
a2[1:,0:2]

array([[4, 5],
       [8, 9]])

In [13]:
# Indexing in 3d array
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
a3[1,0,1]

5

In [15]:
a3[0,0,0]

0

In [16]:
a3[1,1,0]

6

In [17]:
#slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a1[2:5]

array([2, 3, 4])

In [19]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [21]:
a2[-1,-1]

11

In [24]:
a2[-1,-4]

8

In [25]:
a2[-3,-3]

1

In [26]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [27]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [28]:
 a2[1:2,::3]

array([[4, 7]])

In [29]:
# slicing in 3d
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a3[1,:,1]

array([5, 7])

In [32]:
a3 = np.arange(27).reshape(3,3,3)

<IPython.core.display.Javascript object>

In [33]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [36]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
a3[0,1,:]

array([3, 4, 5])

In [38]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [39]:
a3[::2,0:1,::2]

array([[[ 0,  2]],

       [[18, 20]]])

In [40]:
# Iterating in numpy array
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [44]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [45]:
for i in np.nditer(a3):
    print(i)

<IPython.core.display.Javascript object>

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [46]:
# Reshaping

In [47]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
np.transpose(a3)

<IPython.core.display.Javascript object>

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [49]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
# Ravel converts any dimensional array to 1 d array
np.ravel(a3)

<IPython.core.display.Javascript object>

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [54]:
## Stacking 
# Used when data is coming from multiple data sources

In [56]:
# Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [57]:
## Vertical stacking
np.vstack((a4,a5))

<IPython.core.display.Javascript object>

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
# Splitting
# Horizontal Splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
np.hsplit(a2,2)

<IPython.core.display.Javascript object>

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [60]:
np.hsplit(a2,4)

<IPython.core.display.Javascript object>

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [62]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
np.vsplit(a5,3)

<IPython.core.display.Javascript object>

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]